
name: Snake
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Substitua 'x' pela versão do Python desejada
      - name: Install dependencies
        run: pip install -r requirements.txt # Se necessário, altere o nome do arquivo de requisitos
      - name: Run snake
        run: python snake.py # Se necessário, altere o nome do arquivo do jogo Snake
